---
- hosts: all
  become: yes
  vars_files:
    - hadoop_vars.yml

  tasks:
    - name: Configure core-site.xml on each node
      template:
        src: templates/core-site.xml.j2
        dest: "{{ hadoop_home }}/etc/hadoop/core-site.xml"
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_group }}"
        mode: 0644

    - name: Configure hdfs-site.xml on each node
      template:
        src: templates/hdfs-site.xml.j2
        dest: "{{ hadoop_home }}/etc/hadoop/hdfs-site.xml"
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_group }}"
        mode: 0644


- hosts: namenode
  become: yes
  vars_files:
    - hadoop_vars.yml

  tasks:
    - name: Create NameNode directory
      file:
        path: "{{ hdfs_namenode_dir }}"
        state: directory
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_group }}"
        mode: 0755

    - name: Start NameNode service
      shell: "{{ hadoop_home }}/sbin/hadoop-daemon.sh start namenode"
      become: yes


- hosts: datanodes
  become: yes
  vars_files:
    - hadoop_vars.yml

  tasks:
    - name: Create DataNode directory
      file:
        path: "{{ hdfs_datanode_dir }}"
        state: directory
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_group }}"
        mode: 0755

    - name: Start DataNode service
      shell: "{{ hadoop_home }}/sbin/hadoop-daemon.sh start datanode"
      become: yes
